/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApiSchemasMultiEmbeddingsTextEmbeddingInput
 */
public class ApiSchemasMultiEmbeddingsTextEmbeddingInputTest {
    private final ApiSchemasMultiEmbeddingsTextEmbeddingInput model = new ApiSchemasMultiEmbeddingsTextEmbeddingInput();

    /**
     * Model tests for ApiSchemasMultiEmbeddingsTextEmbeddingInput
     */
    @Test
    public void testApiSchemasMultiEmbeddingsTextEmbeddingInput() {
        // TODO: test ApiSchemasMultiEmbeddingsTextEmbeddingInput
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'inputType'
     */
    @Test
    public void inputTypeTest() {
        // TODO: test inputType
    }

    /**
     * Test the property 'encodingFormat'
     */
    @Test
    public void encodingFormatTest() {
        // TODO: test encodingFormat
    }

}
