/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApiSchemasRankUsage
 */
public class ApiSchemasRankUsageTest {
    private final ApiSchemasRankUsage model = new ApiSchemasRankUsage();

    /**
     * Model tests for ApiSchemasRankUsage
     */
    @Test
    public void testApiSchemasRankUsage() {
        // TODO: test ApiSchemasRankUsage
    }

    /**
     * Test the property 'totalTokens'
     */
    @Test
    public void totalTokensTest() {
        // TODO: test totalTokens
    }

    /**
     * Test the property 'promptTokens'
     */
    @Test
    public void promptTokensTest() {
        // TODO: test promptTokens
    }

}
