/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodyStartBulkEmbeddingV1BulkEmbeddingsPost
 */
public class BodyStartBulkEmbeddingV1BulkEmbeddingsPostTest {
    private final BodyStartBulkEmbeddingV1BulkEmbeddingsPost model = new BodyStartBulkEmbeddingV1BulkEmbeddingsPost();

    /**
     * Model tests for BodyStartBulkEmbeddingV1BulkEmbeddingsPost
     */
    @Test
    public void testBodyStartBulkEmbeddingV1BulkEmbeddingsPost() {
        // TODO: test BodyStartBulkEmbeddingV1BulkEmbeddingsPost
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

}
