/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BulkEmbeddingJobStatus
 */
public class BulkEmbeddingJobStatusTest {
    /**
     * Model tests for BulkEmbeddingJobStatus
     */
    @Test
    public void testBulkEmbeddingJobStatus() {
        // TODO: test BulkEmbeddingJobStatus
    }

}
