/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BodyStartBulkEmbeddingV1BulkEmbeddingsPost;
import com.konfigthis.client.model.BulkEmbeddingJobResponse;
import com.konfigthis.client.model.DownloadResultResponse;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BulkEmbeddingsApi
 */
@Disabled
public class BulkEmbeddingsApiTest {

    private static BulkEmbeddingsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BulkEmbeddingsApi(apiClient);
    }

    /**
     * Download Result
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadResultPostTest() throws ApiException {
        String jobId = null;
        DownloadResultResponse response = api.downloadResultPost(jobId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve Job
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobTest() throws ApiException {
        String jobId = null;
        BulkEmbeddingJobResponse response = api.getJob(jobId)
                .execute();
        // TODO: test validations
    }

    /**
     * Start Bulk Embedding
     *
     * Upload a file and get embeddings for each row
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFileAndGetEmbeddingsTest() throws ApiException {
        File _file = null;
        String model = null;
        String email = null;
        BulkEmbeddingJobResponse response = api.uploadFileAndGetEmbeddings(_file, model)
                .email(email)
                .execute();
        // TODO: test validations
    }

}
