/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ApiSchemasMultiEmbeddingsTextEmbeddingInput;
import com.konfigthis.client.model.ColbertModelEmbeddingsOutput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MultiEmbeddingsApi
 */
@Disabled
public class MultiEmbeddingsApiTest {

    private static MultiEmbeddingsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MultiEmbeddingsApi(apiClient);
    }

    /**
     * Create Multi Embeddings
     *
     * Create embedding representations of the given input texts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateEmbeddingsTest() throws ApiException {
        String model = null;
        Object input = null;
        String inputType = null;
        String encodingFormat = null;
        ColbertModelEmbeddingsOutput response = api.generateEmbeddings(model, input)
                .inputType(inputType)
                .encodingFormat(encodingFormat)
                .execute();
        // TODO: test validations
    }

}
