/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.ModelEmbeddingOutput;
import com.konfigthis.client.model.TIEmbeddingInput;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class EmbeddingsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public EmbeddingsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public EmbeddingsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createRepresentationCall(TIEmbeddingInput body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/v1/embeddings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRepresentationValidateBeforeCall(TIEmbeddingInput body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling createRepresentation(Async)");
        }

        return createRepresentationCall(body, _callback);

    }


    private ApiResponse<ModelEmbeddingOutput> createRepresentationWithHttpInfo(TIEmbeddingInput body) throws ApiException {
        okhttp3.Call localVarCall = createRepresentationValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<ModelEmbeddingOutput>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createRepresentationAsync(TIEmbeddingInput body, final ApiCallback<ModelEmbeddingOutput> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRepresentationValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<ModelEmbeddingOutput>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateRepresentationRequestBuilder {
        private String model;
        private Object input;
        private String encodingFormat;

        private CreateRepresentationRequestBuilder() {
        }

        /**
         * Set model
         * @param model The identifier of the model.  Available models and corresponding param size and dimension: - &#x60;jina-embedding-t-en-v1&#x60;, 14m, 312 - &#x60;jina-embedding-s-en-v1&#x60;, 35m, 512 (default) - &#x60;jina-embedding-b-en-v1&#x60;, 110m, 768 - &#x60;jina-embedding-l-en-v1&#x60;, 330, 1024  For more information, please checkout our [technical blog](https://arxiv.org/abs/2307.11224).  (optional)
         * @return CreateRepresentationRequestBuilder
         */
        public CreateRepresentationRequestBuilder model(String model) {
            this.model = model;
            return this;
        }
        
        /**
         * Set input
         * @param input  (optional)
         * @return CreateRepresentationRequestBuilder
         */
        public CreateRepresentationRequestBuilder input(Object input) {
            this.input = input;
            return this;
        }
        
        /**
         * Set encodingFormat
         * @param encodingFormat The format in which you want the embeddings to be returned.Possible value are &#x60;float&#x60; and &#x60;base64&#x60;. Defaults to &#x60;float&#x60; (optional)
         * @return CreateRepresentationRequestBuilder
         */
        public CreateRepresentationRequestBuilder encodingFormat(String encodingFormat) {
            this.encodingFormat = encodingFormat;
            return this;
        }
        
        /**
         * Build call for createRepresentation
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Create embeddings </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            TIEmbeddingInput body = buildBodyParams();
            return createRepresentationCall(body, _callback);
        }

        private TIEmbeddingInput buildBodyParams() {
            TIEmbeddingInput body = new TIEmbeddingInput();
            return body;
        }

        /**
         * Execute createRepresentation request
         * @return ModelEmbeddingOutput
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Create embeddings </td><td>  -  </td></tr>
         </table>
         */
        public ModelEmbeddingOutput execute() throws ApiException {
            TIEmbeddingInput body = buildBodyParams();
            ApiResponse<ModelEmbeddingOutput> localVarResp = createRepresentationWithHttpInfo(body);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createRepresentation request with HTTP info returned
         * @return ApiResponse&lt;ModelEmbeddingOutput&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Create embeddings </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ModelEmbeddingOutput> executeWithHttpInfo() throws ApiException {
            TIEmbeddingInput body = buildBodyParams();
            return createRepresentationWithHttpInfo(body);
        }

        /**
         * Execute createRepresentation request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Create embeddings </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ModelEmbeddingOutput> _callback) throws ApiException {
            TIEmbeddingInput body = buildBodyParams();
            return createRepresentationAsync(body, _callback);
        }
    }

    /**
     * Create Embedding
     * Create embedding representations of the given input texts.
     * @param body  (required)
     * @return CreateRepresentationRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Create embeddings </td><td>  -  </td></tr>
     </table>
     */
    public CreateRepresentationRequestBuilder createRepresentation() throws IllegalArgumentException {
        return new CreateRepresentationRequestBuilder();
    }
}
