/*
 * The Jina Embedding Serving API
 * This is the UniversalAPI to access all the Jina embedding models
 *
 * The version of the OpenAPI document: 0.0.86
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.RankingOutput;
import com.konfigthis.client.model.TextRankInput;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class RerankApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RerankApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public RerankApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call pairRankingCall(TextRankInput textRankInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = textRankInput;

        // create path and map variables
        String localVarPath = "/v1/rerank";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pairRankingValidateBeforeCall(TextRankInput textRankInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'textRankInput' is set
        if (textRankInput == null) {
            throw new ApiException("Missing the required parameter 'textRankInput' when calling pairRanking(Async)");
        }

        return pairRankingCall(textRankInput, _callback);

    }


    private ApiResponse<RankingOutput> pairRankingWithHttpInfo(TextRankInput textRankInput) throws ApiException {
        okhttp3.Call localVarCall = pairRankingValidateBeforeCall(textRankInput, null);
        Type localVarReturnType = new TypeToken<RankingOutput>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call pairRankingAsync(TextRankInput textRankInput, final ApiCallback<RankingOutput> _callback) throws ApiException {

        okhttp3.Call localVarCall = pairRankingValidateBeforeCall(textRankInput, _callback);
        Type localVarReturnType = new TypeToken<RankingOutput>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class PairRankingRequestBuilder {
        private final String model;
        private final Object query;
        private final List<Object> documents;
        private Integer topN;
        private Boolean returnDocuments;

        private PairRankingRequestBuilder(String model, Object query, List<Object> documents) {
            this.model = model;
            this.query = query;
            this.documents = documents;
        }

        /**
         * Set topN
         * @param topN The number of most relevant documents or indices to return, defaults to the length of &#x60;documents&#x60; (optional)
         * @return PairRankingRequestBuilder
         */
        public PairRankingRequestBuilder topN(Integer topN) {
            this.topN = topN;
            return this;
        }
        
        /**
         * Set returnDocuments
         * @param returnDocuments If false, returns results without the doc text - the api will return a list of {index, relevance score} where index is inferred from the list passed into the request. If true, returns results with the doc text passed in - the api will return an ordered list of {index, text, relevance score} where index + text refers to the list passed into the request. Defaults to true (optional, default to true)
         * @return PairRankingRequestBuilder
         */
        public PairRankingRequestBuilder returnDocuments(Boolean returnDocuments) {
            this.returnDocuments = returnDocuments;
            return this;
        }
        
        /**
         * Build call for pairRanking
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Rank output </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            TextRankInput textRankInput = buildBodyParams();
            return pairRankingCall(textRankInput, _callback);
        }

        private TextRankInput buildBodyParams() {
            TextRankInput textRankInput = new TextRankInput();
            textRankInput.model(this.model);
            textRankInput.query(this.query);
            textRankInput.documents(this.documents);
            textRankInput.topN(this.topN);
            textRankInput.returnDocuments(this.returnDocuments);
            return textRankInput;
        }

        /**
         * Execute pairRanking request
         * @return RankingOutput
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Rank output </td><td>  -  </td></tr>
         </table>
         */
        public RankingOutput execute() throws ApiException {
            TextRankInput textRankInput = buildBodyParams();
            ApiResponse<RankingOutput> localVarResp = pairRankingWithHttpInfo(textRankInput);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute pairRanking request with HTTP info returned
         * @return ApiResponse&lt;RankingOutput&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Rank output </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<RankingOutput> executeWithHttpInfo() throws ApiException {
            TextRankInput textRankInput = buildBodyParams();
            return pairRankingWithHttpInfo(textRankInput);
        }

        /**
         * Execute pairRanking request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Rank output </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<RankingOutput> _callback) throws ApiException {
            TextRankInput textRankInput = buildBodyParams();
            return pairRankingAsync(textRankInput, _callback);
        }
    }

    /**
     * Rank
     * Rank pairs.
     * @param textRankInput  (required)
     * @return PairRankingRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Rank output </td><td>  -  </td></tr>
     </table>
     */
    public PairRankingRequestBuilder pairRanking(String model, Object query, List<Object> documents) throws IllegalArgumentException {
        if (model == null) throw new IllegalArgumentException("\"model\" is required but got null");
            

        
        if (documents == null) throw new IllegalArgumentException("\"documents\" is required but got null");
        return new PairRankingRequestBuilder(model, query, documents);
    }
}
